import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillInstagram, AiFillGithub} from 'react-icons/ai';
import Image from "next/legacy/image";
import My from '../public/My.jpeg';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import a1 from '../public/a1.jpg';
import a2 from '../public/a2.jpg';
import a3 from '../public/a3.jpg';
import a4 from '../public/a4.jpg';
import a5 from '../public/a5.jpg';
import a6 from '../public/a6.jpg';
import {useState} from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const toggleMenu = () => {
    setShowMenu(!showMenu);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Richuan_Li's personal zone</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className="min-h-screen">

<nav className="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
  <div className="container flex flex-wrap items-center justify-between mx-auto">
  <a href="https://flowbite.com/" className="flex items-center">
      <img src="https://flowbite.com/docs/images/logo.svg" className="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
      <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
  </a>
  <div className="flex md:order-2">
  <div className="moon-icon ml-auto mr-3 md:mr-6"><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl "/></div>
      <button type="button" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Get started</button>
      <button data-collapse-toggle="navbar-cta" type="button" className="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false" onClick={toggleMenu}>
        <span className="sr-only">Open main menu</span>
        <svg className="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
  <div className={`items-center justify-between w-full md:flex md:w-auto md:order-1 ${showMenu ? '' : 'hidden'}`} id="navbar-cta">
    <ul className="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" aria-current="page">Home</a>
      </li>
      <li>
        <a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
      </li>
      <li>
        <a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
      </li>
      <li>
        <a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
      </li>
    </ul>
  </div>
  </div>
</nav>




            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Welcome to Richuan's zone</h2>
              <h3 className="text-2xl py-2 md:text-3xl">About Me</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto"
              >I am a current computer science student at Dalhousie University, my passion and interest are Software Development, Artificial Intelligence, and Web-app Dev
              To know more about me, hit on the button below to get access to my Linkedlin, IG, and Github</p>
            </div>

            {/* External links to my social accounts */}
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <a href="https://www.linkedin.com/in/richuan-li-karl723/" target="_blank">
              <AiFillLinkedin /></a>
              <a href="https://github.com/Rc620706?tab=repositories" target="_blank">
              <AiFillGithub /></a>
              <a href="https://www.instagram.com" target="_blank">
              <AiFillInstagram /></a>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
              <Image src={My} layout="fill" objectFit="cover"/>
            </div>
          </section>

          <section>
            <div className="text-center p-10">
              <h3 className="text-3xl py-1  text-teal-600 font-medium md:text-3xl">Programming language & Tools I use</h3>
              <p className="text-md py-2 leading-8 text-gray-80">
                PL: Java, Python, SQL, JavaScript <br></br>
                Front-end: HTML, CSS<br></br>
                Framework & Library: React.JS, Next.JS, Spring boot<br></br>
                Tool: MySql, Git, Docker
              </p>
            </div>

            {/* card section */}
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                <Image src={design} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Stunning Designs</h3>
                <p className="py-2">
                  You re the best player in the world, Cristiamao Ronaldo.
                </p>
                <h4 className="py-4">Design too i use</h4>
                <p className="text-gray-800 py-1">ps</p>
                <p className="text-gray-800 py-1">ill</p>
                <p className="text-gray-800 py-1">figma</p>
              </div>

              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
                <Image src={code} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Stunning Designs</h3>
                <p className="py-2">
                  You re the best player in the world, Cristiamao Ronaldo.
                </p>
                <h4 className="py-4">Design too i use</h4>
                <p className="text-gray-800 py-1">ps</p>
                <p className="text-gray-800 py-1">ill</p>
                <p className="text-gray-800 py-1">figma</p>
              </div>

              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
                <Image src={consulting} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Stunning Designs</h3>
                <p className="py-2">
                  You re the best player in the world, Cristiamao Ronaldo.
                </p>
                <h4 className="py-4">Design too i use</h4>
                <p className="text-gray-800 py-1">ps</p>
                <p className="text-gray-800 py-1">ill</p>
                <p className="text-gray-800 py-1">figma</p>
              </div>
            </div>
            {/* card section end*/}
          </section>

          <section>
            <div>
              <h3 className="text-3xl py-1">Photography Protofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-80">
                I am an amateur photographer with <span className="text-teal-500">over 5 years experience</span> in landscape and portrait style Photography.
                These photo present below were taken in 2022, Halifax, Nova Scotia, Canada. 
              </p>
            </div>
            
          </section>
        </main>
      </div>
  )
}
