import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillInstagram, AiFillGithub} from 'react-icons/ai';
import Image from "next/legacy/image";
import My from '../public/My.jpeg';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import a1 from '../public/a1.jpg';
import a2 from '../public/a2.jpg';
import a3 from '../public/a3.jpg';
import a4 from '../public/a4.jpg';
import a5 from '../public/a5.jpg';
import a6 from '../public/a6.jpg';
import {useState} from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Richuan_Li's personal zone</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons">developed</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill 
                    onClick={() => setDarkMode(!darkMode)} 
                    className="cursor-pointer text-2xl"/>
                </li>
                <li>
                  <a 
                    className="bg-gradient-to-r bg-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
                </li>
                <li>
                  <a 
                    className="bg-gradient-to-r bg-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Email</a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Welcome to Richuan's zone</h2>
              <h3 className="text-2xl py-2 md:text-3xl">About Me</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto"
              >I am a current computer science student at Dalhousie University, my passion and interest are Software Development, Artificial Intelligence, and Web-app Dev
              To know more about me, hit on the button below to get access to my Linkedlin, IG, and Github</p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillLinkedin />
              <AiFillGithub />
              <AiFillInstagram />
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
              <Image src={My} layout="fill" objectFit="cover"/>
            </div>
          </section>

          <section>
            <div className="text-center p-10">
              <h3 className="text-3xl py-1  text-teal-600 font-medium md:text-3xl">Programming language & Tools I use</h3>
              <p className="text-md py-2 leading-8 text-gray-80">
                PL: Java, Python, SQL, JavaScript <br></br>
                Front-end: HTML, CSS<br></br>
                Framework & Library: React.JS, Next.JS, Spring boot<br></br>
                Tool: MySql, Git, Docker
              </p>
            </div>

            {/* card section */}
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                <Image src={design} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Stunning Designs</h3>
                <p className="py-2">
                  You re the best player in the world, Cristiamao Ronaldo.
                </p>
                <h4 className="py-4">Design too i use</h4>
                <p className="text-gray-800 py-1">ps</p>
                <p className="text-gray-800 py-1">ill</p>
                <p className="text-gray-800 py-1">figma</p>
              </div>

              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
                <Image src={code} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Stunning Designs</h3>
                <p className="py-2">
                  You re the best player in the world, Cristiamao Ronaldo.
                </p>
                <h4 className="py-4">Design too i use</h4>
                <p className="text-gray-800 py-1">ps</p>
                <p className="text-gray-800 py-1">ill</p>
                <p className="text-gray-800 py-1">figma</p>
              </div>

              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
                <Image src={consulting} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Stunning Designs</h3>
                <p className="py-2">
                  You re the best player in the world, Cristiamao Ronaldo.
                </p>
                <h4 className="py-4">Design too i use</h4>
                <p className="text-gray-800 py-1">ps</p>
                <p className="text-gray-800 py-1">ill</p>
                <p className="text-gray-800 py-1">figma</p>
              </div>
            </div>
            {/* card section end*/}
          </section>

          <section>
            <div>
              <h3 className="text-3xl py-1">Photography Protofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-80">
                I am an amateur photographer with <span className="text-teal-500">over 5 years experience</span> in landscape and portrait style Photography.
                These photo present below were taken in 2022, Halifax, Nova Scotia, Canada. 
              </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image 
                src={a1} 
                className="rounded-lg object-cover" 
                width={"100"} 
                height={"100"} 
                layout="responsive"/>
              </div>

              <div className="basis-1/3 flex-1">
                <Image 
                src={a2} 
                className="rounded-lg object-cover" 
                width={"100"} 
                height={"100"} 
                layout="responsive"/>
              </div>

              <div className="basis-1/3 flex-1">
                <Image 
                src={a3} 
                className="rounded-lg object-cover" 
                width={"100"} 
                height={"100"} 
                layout="responsive"/>
              </div>

              <div className="basis-1/3 flex-1">
                <Image 
                src={a4} 
                className="rounded-lg object-cover" 
                width={"100"} 
                height={"100"} 
                layout="responsive"/>
              </div>

              <div className="basis-1/3 flex-1">
                <Image 
                src={a5} 
                className="rounded-lg object-cover" 
                width={"100"} 
                height={"100"} 
                layout="responsive"/>
              </div>

              <div className="basis-1/3 flex-1">
                <Image 
                src={a6} 
                className="rounded-lg object-cover" 
                width={"100"} 
                height={"100"} 
                layout="responsive"/>
                </div>
            </div>
          </section>
        </main>
      </div>
  )
}
